api = "0.7"

[extension]
id = "redhat-runtimes/nodejs"
name = "RedHat Runtimes Node.js Dependency Extension"
version = "0.0.1"
description = "This extension installs the appropriate nodejs runtime via dnf"

[metadata]
  [metadata.default-versions]
    node = "18.*.*"

  [[metadata.dependencies]]
    id = "node"
    name = "Ubi Node Extension"
    stacks = ["ubi8-paketo"]
    source = "172.17.0.1:5000/ubi8-paketo-run-nodejs-18"
    version = "18"

  [[metadata.dependencies]]
    id = "node"
    name = "Ubi Node Extension"
    stacks = ["ubi8-paketo"]
    source = "172.17.0.1:5000/ubi8-paketo-run-nodejs-16"
    version = "16"